### ISSUE TITLE
error in firefox on win 7

### ISSUE THREAD

**Issue by bendacoder** [dotjersh/dotjersh.github.io#2]
When visiting the webpage through Firefox (version 49.0.2 on Windows 7 Enterprise) the items appear stacked on top of each other instead of being organized in a grid (see attached image). The monitor resolution is 1200x700. How do I fix this error? Thank you in advance!

![dotjersh-error](https://cloud.githubusercontent.com/assets/13733017/26168847/a0cf46bc-3b09-11e7-8b93-ad47ed20dcd9.png)

**Comment by dotjersh** [comment]
Alas, Firefox does not support the new css3 columns. Good to know, I'll fix it as soon as possible, thank you my good man.

**Comment by dotjersh** [comment]
Not supported by most browsers. I guess I'd better add legacy support.

http://caniuse.com/#search=column

**Comment by bendacoder** [comment]
Dammit Firefox! You're supposed to be Open Source and good =(
